import { createStyles } from 'antd-style';
import { color, font, fontSize, radius, space, transition } from '../../../theme/tokens';

export const useGoalColumnStyles = createStyles(() => ({
  column: {
    background: 'transparent',
    border: `1px solid ${color.border.goalColumn}`,
    borderRadius: radius.lg1,
    padding: `${space.md2}px ${space.md1}px ${space.sm3}px`,
    minHeight: 200,
    display: 'flex',
    flexDirection: 'column',
    gap: space.sm2,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  title: {
    fontFamily: font.heading,
    fontSize: fontSize.md17,
    fontWeight: 600,
    color: color.text.title,
  },
  summary: {
    fontSize: fontSize.sm,
    color: color.text.label,
  },
  track: {
    height: 4,
    borderRadius: radius.xs,
    background: color.neutral.barTrackAlt,
    overflow: 'hidden',
  },
  fill: {
    height: '100%',
    background: color.lime.text,
    transition: transition.xpBar,
  },
  addButton: {
    marginTop: 'auto',
    border: `1px dashed ${color.border.dashed}`,
    borderRadius: radius.sm5,
    padding: `${space.xs4}px ${space.sm1}px`,
    fontSize: fontSize.sm13,
    color: color.text.label,
    background: 'none',
    cursor: 'pointer',
    textAlign: 'left',
    '&:hover': { borderColor: color.lime.text, color: color.lime.text },
  },
  addArea: {
    width: '100%',
    background: color.surface.field,
    border: `1px solid ${color.border.fieldFocus}`,
    borderRadius: radius.sm3,
    padding: space.xs3,
    fontSize: fontSize.md,
    color: color.text.card,
    fontFamily: font.body,
    resize: 'none',
    boxSizing: 'border-box',
  },
}));

export const useGoalCardStyles = createStyles(() => ({
  card: {
    background: color.surface.column,
    border: `1px solid ${color.border.goalCard}`,
    borderRadius: radius.md1,
    padding: `${space.thirteen}px ${space.thirteen}px ${space.sm2}px`,
    display: 'flex',
    gap: space.sm2,
    alignItems: 'flex-start',
    '&:hover': { borderColor: color.border.cardHover },
  },
  checkbox: {
    width: 18,
    height: 18,
    minWidth: 18,
    borderRadius: radius.sm1,
    border: `1px solid ${color.border.checkboxIdle}`,
    background: 'transparent',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    marginTop: 1,
    '&:hover': { borderColor: color.lime.text, background: color.lime.surfaceGoalHover },
  },
  checkboxDone: {
    background: color.lime.text,
    borderColor: color.lime.text,
  },
  check: {
    fontSize: 12,
    fontWeight: 700,
    color: color.lime.onLime,
  },
  title: {
    flex: 1,
    fontSize: fontSize.md14_5,
    lineHeight: 1.45,
    color: color.text.card,
  },
  titleDone: {
    color: color.text.counter,
    textDecoration: 'line-through',
  },
  editArea: {
    flex: 1,
    background: color.surface.field,
    border: `1px solid ${color.border.fieldFocus}`,
    borderRadius: radius.sm3,
    padding: space.xs3,
    fontSize: fontSize.md14_5,
    color: color.text.card,
    fontFamily: font.body,
    resize: 'none',
  },
  removeButton: {
    background: 'none',
    border: 'none',
    fontSize: fontSize.md15,
    color: color.text.icon,
    cursor: 'pointer',
    '&:hover': { color: color.coral.text },
  },
}));
